import { logger } from '.';

// cspell-checker: disable
const EVENT_LIST = [
  'onAbort',
  'onAfterprint',
  'onAnimationend',
  'onAnimationiteration',
  'onAnimationstart',
  'onAudioprocess',
  'onBeforeprint',
  'onBeforeunload',
  'onBeginEvent',
  'onBlocked',
  'onBlur',
  'onCached',
  'onCanplay',
  'onCanplaythrough',
  'onChange',
  'onChargingchange',
  'onChargingtimechange',
  'onChecking',
  'onClick',
  'onClose',
  'onCompassneedscalibration',
  'onComplete',
  'onCompositionend',
  'onCompositionstart',
  'onCompositionupdate',
  'onContextmenu',
  'onCopy',
  'onCut',
  'onDblclick',
  'onDevicelight',
  'onDevicemotion',
  'onDeviceorientation',
  'onDeviceproximity',
  'onDischargingtimechange',
  'onDOMActivate',
  'onDOMAttributeNameChanged',
  'onDOMAttrModified',
  'onDOMCharacterDataModified',
  'onDOMContentLoaded',
  'onDOMElementNameChanged',
  'onDOMFocusIn',
  'onDOMFocusOut',
  'onDOMNodeInserted',
  'onDOMNodeInsertedIntoDocument',
  'onDOMNodeRemoved',
  'onDOMNodeRemovedFromDocument',
  'onDOMSubtreeModified',
  'onDownloading',
  'onDrag',
  'onDragend',
  'onDragenter',
  'onDragleave',
  'onDragover',
  'onDragstart',
  'onDrop',
  'onDurationchange',
  'onEmptied',
  'onEnded',
  'onEndEvent',
  'onError',
  'onFocus',
  'onFocusin',
  'onFocusout',
  'onFullscreenchange',
  'onFullscreenerror',
  'onGamepadconnected',
  'onGamepaddisconnected',
  'onHashchange',
  'onInput',
  'onInvalid',
  'onKeydown',
  'onKeypress',
  'onKeyup',
  'onLanguagechange',
  'onLevelchange',
  'onLoad',
  'onLoadeddata',
  'onLoadedmetadata',
  'onLoadend',
  'onLoadstart',
  'onMessage',
  'onMousedown',
  'onMouseenter',
  'onMouseleave',
  'onMousemove',
  'onMouseout',
  'onMouseover',
  'onMouseup',
  'onNoupdate',
  'onObsolete',
  'onOffline',
  'onOnline',
  'onOpen',
  'onOrientationchange',
  'onPagehide',
  'onPageshow',
  'onPaste',
  'onPause',
  'onPointerlockchange',
  'onPointerlockerror',
  'onPlay',
  'onPlaying',
  'onPopstate',
  'onProgress',
  'onRatechange',
  'onReadystatechange',
  'onRepeatevent',
  'onReset',
  'onResize',
  'onScroll',
  'onSeeked',
  'onSeeking',
  'onSelect',
  'onShow',
  'onStalled',
  'onStorage',
  'onSubmit',
  'onSuccess',
  'onSuspend',
  'onSVGAbort',
  'onSVGError',
  'onSVGLoad',
  'onSVGResize',
  'onSVGScroll',
  'onSVGUnload',
  'onSVGZoom',
  'onTimeout',
  'onTimeupdate',
  'onTouchcancel',
  'onTouchend',
  'onTouchenter',
  'onTouchleave',
  'onTouchmove',
  'onTouchstart',
  'onTransitionend',
  'onUnload',
  'onUpdateready',
  'onUpgradeneeded',
  'onUserproximity',
  'onVersionchange',
  'onVisibilitychange',
  'onVolumechange',
  'onWaiting',
  'onWheel',
];
// cspell-checker: enable

// report any error that would be fired from an event handler
const monitorUserEventsErrors = () => {
  window.addEventListener('error', (event) => {
    if (!event.error) return; // the error can be safely ignored
    const { message, stack } = event.error;
    // eslint-disable-next-line no-restricted-syntax
    for (const evt of EVENT_LIST) {
      if (stack.includes(`at ${evt}`)) {
        logger.error(`[${evt}] ${message}`, { stack });
        return;
      }
    }
  });
};

export default monitorUserEventsErrors;
